version: '3.7'
services:
  database:
    image: postgres
    container_name: crud_teddy
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=teddy
      - POSTGRES_PASSWORD=teddy
      - POSTGRES_DB=teddy
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: teddy_app
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    network_mode: host
volumes:
  pgdata:
    driver: local
